### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kasbah** [privalytics/privalytics.io#7]
Hello, I was just looking at privalytics to make a publicly viewable stats page for https://kitspace.org. (Also signed up at privalytics.io but it said you are at capacity.)

I was wondering what you'd like people to be able to do with the code. Copy, self-host, modify etc. ?

**Comment by aquilesC** [comment]
Hello! 

I made a very bad mistake when I started this project, which was going for a non-free template for the website that I can't publicly share. This means that I have a template for the website itself and a template for the open-source version, which inevitably went out of sync and, as you see, it does not work now. 

So, with the code you can do whatever you like. I have just now realized that I never picked a license for it, which I should add to my todo's. For the time being assuming AGPLv3 is fine, I will probably go for a more permissive one.
