### ISSUE TITLE
Is this self-hostable?

### ISSUE THREAD

**Issue by kasbah** [privalytics/privalytics.io#8]
I partly managed to figure out how to run this on my machine. I did:

```
pip3 install -r requirements.txt
python3 manage.py runserver
````

I get a (older?) version of the privalitcs.io site, but it doesn't seem possible to create a user in it (the page is full of errors). Is it possible to self-host this?

**Comment by aquilesC** [comment]
I briefly answered the problems on #7 . The core problem right now is that the template I use in privalytics.io is *proprietary* ([the saas](https://themeforest.net/item/thesaas-responsive-saas-software-webapp-wordpress-theme/20136366?gclid=Cj0KCQjwuJz3BRDTARIsAMg-HxXYPOGffLOFB3lZ8yEjzc4q_UObtN4ZDKhfBXi9KJ7hVYQ9l42SttwaAn8iEALw_wcB)) and the one on the repository ended up being out of sync. 

I will pick up the development at a later stage, right now I am focused on other things, but you are more than free to contribute pull requests if you find your way around it.

**Comment by kasbah** [comment]
Ok, thank you very much for responding to my issues.
